apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest
  name: kbe-rest
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kbe-rest
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kbe-rest
  name: kbe-rest
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kbe-rest
  type: ClusterIP
status:
  loadBalancer: {}
